apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeapi
  template:
    metadata:
      labels:
        app: kubeapi
    spec:
      containers:
        - name: kubeapi
          image: vramakacr2.azurecr.io/kubeapi:ab49c2c6bfdb102f1296bfc0d08ffa1b9d6bde1f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: kubeapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: kubeapi